name: Update website

on:
  # Required for reusable workflows
  workflow_call:
    inputs:
      SIS_SUBJECT_AREA:
        required: true
        type: string
      SIS_CATALOG_NUMBER:
        required: true
        type: string
      AUTHOR:
        required: true
        type: string
      GOOGLE_ANALYTICS_TAG:
        required: true
        type: string
      COURSE_DATA_FILE:
        required: false
        type: string
        default: '/dev/null'
      GIT_NAME:
        required: true
        type: string
      GIT_EMAIL:
        required: true
        type: string
    secrets:
      SIS_COURSE_API_ID:
        required: true
      SIS_COURSE_API_KEY:
        required: true
      CALLER_GITHUB_TOKEN:
        required: true
  workflow_dispatch:
  schedule:
    - cron: "5 2 1 * *"
  #push:
  #  branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        if [ -f .github/scripts/requirements.txt ]; then
            pip install -r .github/scripts/requirements.txt
        fi

    - name: Configure git identity
      env:
        GITHUB_TOKEN: ${{ secrets.CALLER_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
        GIT_NAME: ${{ vars.GIT_NAME }}
        GIT_EMAIL: ${{ vars.GIT_EMAIL }}
      run: |
        git config --global user.name "${GIT_NAME}"
        git config --global user.email "${GIT_EMAIL}"

    - name: Run script
      env:
        SIS_COURSE_API_ID: ${{ secrets.SIS_COURSE_API_ID }}
        SIS_COURSE_API_KEY: ${{ secrets.SIS_COURSE_API_KEY }}
        SIS_SUBJECT_AREA: ${{ vars.SIS_SUBJECT_AREA }}
        SIS_CATALOG_NUMBER: ${{ vars.SIS_CATALOG_NUMBER }}
        AUTHOR: ${{ vars.AUTHOR }}
        GOOGLE_ANALYTICS_TAG: ${{ vars.GOOGLE_ANALYTICS_TAG }}
        COURSE_DATA_FILE: ${{ vars.COURSE_DATA_FILE || '/dev/null' }}
      run: |
        python .github/scripts/render-templates.py \
          --subject-area=${SIS_SUBJECT_AREA} \
          --catalog-number=${SIS_CATALOG_NUMBER} \
          --author=${AUTHOR} \
          --google-analytics-tag=${GOOGLE_ANALYTICS_TAG} \
          --course-data-file=${COURSE_DATA_FILE}

    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

    - name: Commit and push changes
      if: steps.git-check.outputs.changes == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.CALLER_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
      run: |
        git add .
        git commit -m "Update via GitHub Actions."
        git push
